def grade(tmnHorizontalGrade):
    print("+"+"-"*tmnHorizontalGrade+"+"+"-"*tmnHorizontalGrade+"+")
    print("|"+" "*tmnHorizontalGrade+"|"+" "*tmnHorizontalGrade+"|")
    print("|"+" "*tmnHorizontalGrade+"|"+" "*tmnHorizontalGrade+"|")
    print("|"+" "*tmnHorizontalGrade+"|"+" "*tmnHorizontalGrade+"|")
    print("|"+" "*tmnHorizontalGrade+"|"+" "*tmnHorizontalGrade+"|")
    print("+"+"-"*tmnHorizontalGrade+"+"+"-"*tmnHorizontalGrade+"+")
    print("|"+" "*tmnHorizontalGrade+"|"+" "*tmnHorizontalGrade+"|")
    print("|"+" "*tmnHorizontalGrade+"|"+" "*tmnHorizontalGrade+"|")
    print("|"+" "*tmnHorizontalGrade+"|"+" "*tmnHorizontalGrade+"|")
    print("|"+" "*tmnHorizontalGrade+"|"+" "*tmnHorizontalGrade+"|")
    print("+"+"-"*tmnHorizontalGrade+"+"+"-"*tmnHorizontalGrade+"+")
grade(10)